In [3]:
import os
import numpy as np
import tensorflow as tf
from tensorflow import keras
import cv2 as cv
from keras import layers, utils, models, callbacks as cb

In [15]:
# model = models.load_model(r'E:\University\Semester 6\Grad\tile classifciation\thing.h5')

In [16]:
# def predict(img_array):
#     predictions = model.predict(img_array)
# #predictions[:5]
#     score = predictions[0]
#     x = np.argmax(score)
# #print(score)
#     print(f"This is tile number {x+1}" )

In [17]:
# cap = cv.VideoCapture(0)
# while (cap.isOpened()):
#     ret,frame=cap.read()
#     if ret==True:
#         cv.imshow('frame',frame)
#         img=frame
#         #img = img.resize((540,960))
#         frame_array = keras.preprocessing.image.img_to_array(img)
#         frame_array = tf.expand_dims(frame_array, 0)
#         predict(img_array=frame_array)
#         if cv.waitKey(25) & 0xFF==ord('q'):
#             break
# cap.release()
# cv.destroyAllWindows()

In [4]:
model = models.load_model(r'E:\University\Semester 6\Grad\tile classification 2\tile classifciation\thing5.h5')

In [19]:

#path: str = r'E:\University\Semester 6\Grad\tile classifciation\tile1.jpg'
#path: str = r'E:\University\Semester 6\Grad\tile classifciation\tile2.jpg'
#path: str = r'E:\University\Semester 6\Grad\tile classifciation\tile3.jpg'
#path: str = r'E:\University\Semester 6\Grad\tile classifciation\tile4.jpg'

#path: str = r'E:\University\Semester 6\Grad\tile classifciation\testing\tile1.jpg'
#path: str = r'E:\University\Semester 6\Grad\tile classifciation\validation\tile5\tile5_frame46.jpg'
#path: str = r'E:\University\Semester 6\Grad\tile classifciation\testing\tile3.jpg'
#path: str = r'E:\University\Semester 6\Grad\tile classifciation\testing\tile4.jpg'
# path: str = r'E:\University\Semester 6\Grad\tile classifciation\testing\tile5.jpg'


In [20]:
img = keras.preprocessing.image.load_img(
    path,
    target_size=(540,960)
)

img_array = keras.preprocessing.image.img_to_array(img)
img_array = tf.expand_dims(img_array, 0)

NameError: name 'path' is not defined

In [ ]:
predictions = model.predict(img_array)
#predictions[:5]
score = predictions[0]
x = np.argmax(score)
print(score)
print(f"This is tile number {x+1}" )

1/1 [==============================] - 0s 111ms/step
[4.8837972e-16 8.8456606e-19 7.2328845e-04 1.8307726e-14 9.9927670e-01]
This is tile number 5


In [6]:
def find_high_acc(prefix):
  os.chdir(prefix)

  for i, prefix in enumerate(os.listdir('.')):
    img = keras.preprocessing.image.load_img(
    prefix,
    target_size=(540,960)
    )

    img_array = keras.preprocessing.image.img_to_array(img)
    img_array = tf.expand_dims(img_array, 0)
    predictions = model.predict(img_array)
    #predictions[:5]
    score = predictions[0]
    x = np.argmax(score)
    print(score)
    print(f"This is tile number {x+1}" )




print(find_high_acc(r'E:\University\Semester 6\Grad\tile classification 2\tile classifciation\validation\tile4\\'))

1/1 [==============================] - 0s 75ms/step
[0.22253568 0.21921611 0.20457035 0.20436595 0.14931199]
This is tile number 1
1/1 [==============================] - 0s 77ms/step
[0.22253568 0.21921611 0.20457035 0.20436595 0.14931199]
This is tile number 1
1/1 [==============================] - 0s 73ms/step
[0.22253568 0.21921611 0.20457035 0.20436595 0.14931199]
This is tile number 1
1/1 [==============================] - 0s 75ms/step
[0.22253568 0.21921611 0.20457035 0.20436595 0.14931199]
This is tile number 1
1/1 [==============================] - 0s 75ms/step
[0.22253568 0.21921611 0.20457035 0.20436595 0.14931199]
This is tile number 1
1/1 [==============================] - 0s 73ms/step
[0.22253568 0.21921611 0.20457035 0.20436595 0.14931199]
This is tile number 1
1/1 [==============================] - 0s 73ms/step
[0.22253568 0.21921611 0.20457035 0.20436595 0.14931199]
This is tile number 1
1/1 [==============================] - 0s 74ms/step
[0.22253568 0.21921611 0.204570

In [41]:
import os
path = os.chdir(r"E:\University\Semester 6\Grad\tile classification 2\tile classifciation\training\tile1")
# print(path)
i=1
# os.chdir('training')
# for category in os.listdir(r'.'):
#   os.chdir(category)

for file in os.listdir(path):
  new_file_name = "pic{}.jpg".format(i)
  os.rename(file,new_file_name)
  i=i+1